clean_typhoon_forecast_data <- function(datamatrix_Hazard_impact_static) {
#-------------------------Examine final dataset---------------------------------
data.training <- datamatrix_Hazard_impact_static %>% # arrange(typhoon_name,Mun_Code) %>%
   dplyr::mutate(index                          = 1:nrow(datamatrix_Hazard_impact_static),
    GEN_typhoon_name         = typhoon_name,
    GEN_landslide                  =landslide_per,
    GEN_landslide_y               =Yel_per_LSSAb,
    GEN_landslide_o                 =Or_per_LSblg,
    GEN_landslide_r                 =Red_per_LSbldg,
    GEN_stormsurge                 =stormsurge_per,
    GEN_stormsurge_y                 =Yellow_per_LSbl,
    GEN_stormsurge_o                 =OR_per_SSAbldg,
    GEN_stormsurge_r                 =RED_per_SSAbldg,
    WEA_gust_dur                   =gust_dur,
    WEA_sust_dur                   =sust_dur,
    WEA_vmax_gust                  =vmax_gust,
    WEA_vmax_sust                  =vmax_sust,
    WEA_vmax_gust_mhp              =vmax_gust_mph,
    WEA_vmax_sust_mhp              =vmax_sust_mph,
    WEA_vmax_gust_sqr              =vmax_sust_mph^2,
    WEA_vmax_sust_sqr              =vmax_sust_mph^2,
    WEA_vmax_sust_cube             =vmax_sust_mph^3,
    WEA_vmax_gust_cube             =vmax_sust_mph^3,
    WEA_dist_track                 =dist_track,
    GEN_mun_code                   = Mun_Code,
    #GEN_prov_name                  = Province,
    GEN_mun_name                   = Mun_Name,
    WEA_windspeed                  = vmax_sust_mph,
    WEA_windspeed_squared          = vmax_sust_mph^2,
    WEA_windspeed_cube             = vmax_sust_mph^3,
    WEA_rainfall_max               = rainfall_24h,
    #WEA_rainfall_sum               = ranfall_sum,
    #POS_distance_first_impact      = distance_first_impact,
    #POS_distance_typhoon           = distance_typhoon_km,
    GEO_slope_mean                 = mean_slope,
    GEO_slope_stdev                = slope_stdev,
    GEO_ruggedness_mean            = mean_ruggedness,
    GEO_ruggedness_stdev           = ruggedness_stdev,
    GEO_elevation_mean             = mean_elevation_m,
    GEO_coast_length               = ifelse(is.na(coast_length),0,coast_length),
    GEO_coast_yn                   = with_coast,
    GEO_Area                       = area_km2,
    GEO_perimeter                  = perimeter,
    #GEO_poverty_perc               = poverty_perc,
    #GEO_pop_density_15             = pop_density_15,
    #GEO_pop_15                     = pop_15,
    GEO_n_households               = Housing.Units,
    #GEO_coast_altitude             = ifelse(GEO_coast_yn ==1 & GEO_elevation_mean > 100, 'High coast',
    #                                        ifelse(GEO_coast_yn==1 & GEO_elevation_mean <= 100, 'Low coast', 'No coast')),
    MAT_Strong.Roof.Strong.Wall                =Strong.Roof.Strong.Wall,
    MAT_Strong.Roof.Light.Wall                 =Strong.Roof.Light.Wall,
    MAT_Strong.Roof.Salvage.Wall               =Strong.Roof.Salvage.Wall,
    MAT_Light.Roof.Strong.Wall                 =Light.Roof.Strong.Wall,
    MAT_Light.Roof.Light.Wall                  =Light.Roof.Light.Wall,
    MAT_Light.Roof.Salvage.Wall                =Light.Roof.Salvage.Wall,
    MAT_Salvaged.Roof.Strong.Wall              =Salvaged.Roof.Strong.Wall,
    MAT_Salvaged.Roof.Light.Wall               =Salvaged.Roof.Light.Wall,
    MAT_Salvaged.Roof.Salvage.Wall             =Salvaged.Roof.Salvage.Wall,
    #MAT_wall_bamboo                = wall_bamboo,
    INT_rainfall_landslide          = landslide_per * rainfall_24h,
    INT_windspeed_Strong.Roof.Strong.Wall            = vmax_sust_mph * Strong.Roof.Strong.Wall,
    INT_windspeed_Strong.Roof.Light.Wall             = vmax_sust_mph * Strong.Roof.Light.Wall,
    INT_windspeed_Strong.Roof.Salvage.Wall           = vmax_sust_mph * Strong.Roof.Salvage.Wall,
    INT_windspeed_Light.Roof.Strong.Wall             = vmax_sust_mph * Light.Roof.Strong.Wall,
    INT_windspeed_Light.Roof.Light.Wall              = vmax_sust_mph * Light.Roof.Light.Wall,
    INT_windspeed_Light.Roof.Salvage.Wall            = vmax_sust_mph * Light.Roof.Salvage.Wall,
    INT_windspeed_Salvaged.Roof.Strong.Wall          = vmax_sust_mph * Salvaged.Roof.Strong.Wall,
    INT_windspeed_Salvaged.Roof.Light.Wall           = vmax_sust_mph * Salvaged.Roof.Light.Wall,
    INT_windspeed_Salvaged.Roof.Salvage.Wall         = vmax_sust_mph * Salvaged.Roof.Salvage.Wall,
    INT_windspeed_cube_Strong.Roof.Strong.Wall       = vmax_sust_mph^3  * Strong.Roof.Strong.Wall,
    INT_windspeed_cube_Strong.Roof.Light.Wall        = vmax_sust_mph^3  * Strong.Roof.Light.Wall,
    INT_windspeed_cube_Strong.Roof.Salvage.Wall      = vmax_sust_mph^3  * Strong.Roof.Salvage.Wall,
    INT_windspeed_cube_Light.Roof.Strong.Wall        = vmax_sust_mph^3  * Light.Roof.Strong.Wall,
    INT_windspeed_cube_Light.Roof.Light.Wall         = vmax_sust_mph^3  * Light.Roof.Light.Wall,
    INT_windspeed_cube_Light.Roof.Salvage.Wall       = vmax_sust_mph^3  * Light.Roof.Salvage.Wall,
    INT_windspeed_cube_Salvaged.Roof.Strong.Wall     = vmax_sust_mph^3  * Salvaged.Roof.Strong.Wall,
    INT_windspeed_cube_Salvaged.Roof.Light.Wall      = vmax_sust_mph^3  * Salvaged.Roof.Light.Wall,
    INT_windspeed_cube_Salvaged.Roof.Salvage.Wall    = vmax_sust_mph^3  * Salvaged.Roof.Salvage.Wall,
    INT_windspeed_coast_yn                           = vmax_sust_mph * with_coast,
    INT_windspeed_cube_coast_yn                      = vmax_sust_mph^3 * with_coast,
    INT_coast_yn_elevation                           = with_coast * mean_elevation_m

  ) %>%
   dplyr::select (index,
		  GEN_mun_code,
          GEN_mun_name,
          GEN_typhoon_name,
		  GEO_n_households,
          GEN_landslide,
          GEN_landslide_y,
          GEN_landslide_o,
          GEN_landslide_r,
          GEN_stormsurge,
          GEN_stormsurge_y,
          GEN_stormsurge_o,
          GEN_stormsurge_r,
          WEA_gust_dur,
          WEA_sust_dur,
          #WEA_vmax_gust,
          #WEA_vmax_sust,
          #WEA_vmax_gust_mhp,
          WEA_vmax_sust_mhp,
          #WEA_vmax_gust_sqr,
          WEA_vmax_sust_sqr,
          WEA_vmax_sust_cube,
          #WEA_vmax_gust_cube,
          WEA_dist_track,
          #WEA_windspeed,
          #WEA_windspeed_squared,
          #WEA_windspeed_cube,
          WEA_rainfall_max,
          #WEA_rainfall_sum,
          GEO_slope_mean,
          GEO_slope_stdev,
          GEO_ruggedness_mean,
          GEO_ruggedness_stdev,
          GEO_elevation_mean,
          GEO_coast_length,
          GEO_coast_yn,
          GEO_Area,
          GEO_perimeter,
          #GEO_poverty_perc,
          #GEO_pop_density_15,
          #GEO_pop_15,
          MAT_Strong.Roof.Strong.Wall,
          MAT_Strong.Roof.Light.Wall,
          MAT_Strong.Roof.Salvage.Wall,
          MAT_Light.Roof.Strong.Wall,
          MAT_Light.Roof.Light.Wall,
          MAT_Light.Roof.Salvage.Wall,
          MAT_Salvaged.Roof.Strong.Wall,
          MAT_Salvaged.Roof.Light.Wall,
          MAT_Salvaged.Roof.Salvage.Wall,
          INT_rainfall_landslide,
          INT_windspeed_Strong.Roof.Strong.Wall,
          INT_windspeed_Strong.Roof.Light.Wall,
          INT_windspeed_Strong.Roof.Salvage.Wall,
          INT_windspeed_Light.Roof.Strong.Wall,
          INT_windspeed_Light.Roof.Light.Wall,
          INT_windspeed_Light.Roof.Salvage.Wall,
          INT_windspeed_Salvaged.Roof.Strong.Wall,
          INT_windspeed_Salvaged.Roof.Light.Wall,
          INT_windspeed_Salvaged.Roof.Salvage.Wall,
          INT_windspeed_cube_Strong.Roof.Strong.Wall,
          INT_windspeed_cube_Strong.Roof.Light.Wall,
          INT_windspeed_cube_Strong.Roof.Salvage.Wall,
          INT_windspeed_cube_Light.Roof.Strong.Wall,
          INT_windspeed_cube_Light.Roof.Light.Wall,
          INT_windspeed_cube_Light.Roof.Salvage.Wall,
          INT_windspeed_cube_Salvaged.Roof.Strong.Wall,
          INT_windspeed_cube_Salvaged.Roof.Light.Wall,
          INT_windspeed_cube_Salvaged.Roof.Salvage.Wall,
          INT_windspeed_coast_yn,
          INT_windspeed_cube_coast_yn,
          INT_coast_yn_elevation)
  return(data.training)
}
