#------------------------  Load required packages ------------------------------

# Load required packages: 

library(dplyr)
library(ranger)
library(caret)
library(randomForest)
library(broom)
library(tidyr)
library(stringr)


clean_typhoon_data_forecast <- function(data_for) {
#-------------------------group dataset---------------------------------
data.training <- data_for %>%
  dplyr::arrange(GEN_typhoon_name,GEN_mun_code) %>%
  dplyr::mutate(
    index                          = 1:nrow(data_for),
    GEN_typhoon_name               = GEN_typhoon_name,
    WEA_gust_dur                   =gust_dur,
    WEA_sust_dur                   =sust_dur,
    #WEA_vmax_gust                  =vmax_gust,
    #WEA_vmax_sust                  =vmax_sust,
    WEA_vmax_gust_mhp              =vmax_gust_mph,
    WEA_vmax_sust_mhp              =vmax_sust_mph,
    WEA_vmax_gust_sqr              =vmax_gust_mph^2,
    WEA_vmax_sust_sqr              =vmax_sust_mph^2,
    WEA_vmax_sust_cube             =vmax_sust_mph^3,
    WEA_vmax_gust_cube             =vmax_gust_mph^3,
    WEA_dist_track                 =dist_track,
    WEA_vmax_sust_mhp              =vmax_sust_mph,
    #GEN_prov_name                  = Province,
    #GEN_mun_name                   = Municipality_City,
    #DAM_comp_houses                = Totally,
    #DAM_part_houses                = Partially,
    #DAM_tot_houses                 = total,
    #DAM_tot_houses_0p25weight      = total_damage_houses_0p25weight,
    #DAM_comp_houses_perc           = 100*(Totally/Housing.Units),
    #DAM_part_houses_perc           = 100*(Partially/Housing.Units) ,
    #DAM_tot_houses_perc            = 100*(total/Housing.Units),
    #DAM_tot_houses_0p25weight_perc = total_damage_houses_0p25weight_perc,
    WEA_windspeed                  = vmax_sust_mph,
    WEA_windspeed_squared          = vmax_sust_mph^2,
    WEA_windspeed_cube             = vmax_sust_mph^3,
    #WEA_rainfall_max               = rainfll_max,
    #WEA_rainfall_sum               = ranfall_sum,
    #WEA_rainfall_max1             = ifelse(WEA_rainfall_max > 350, 1,0), #ifelse(WEA_rainfall_max <= 350, 0, 0)),
    #POS_distance_first_impact      = distance_first_impact,
    #POS_distance_typhoon           = distance_typhoon_km,
    #GEO_slope_mean                 = mean_slope,
    #GEO_slope_stdev                = slope_stdev,
    #GEO_ruggedness_mean            = mean_ruggedness,
    #GEO_ruggedness_stdev           = ruggedness_stdev,
    #GEO_elevation_mean             = mean_elevation_m,
    #GEO_coast_length               = ifelse(is.na(coast_length),0,coast_length),
    #GEO_coast_yn                   = with_coast,
    #GEO_Area                       = area_km2,
    #GEO_perimeter                  = perimeter,
    #GEO_poverty_perc               = poverty_perc,
    #GEO_pop_density_15             = pop_density_15,
    #GEO_pop_15                     = pop_15,
    #GEO_n_households               = Housing.Units,
    #GEO_coast_altitude             = ifelse(GEO_coast_yn ==1 & GEO_elevation_mean > 100, 'High coast',
    #                                        ifelse(GEO_coast_yn==1 & GEO_elevation_mean <= 100, 'Low coast', 'No coast')),
    #MAT_Strong.Roof.Strong.Wall                =Strong.Roof.Strong.Wall,
    #MAT_Strong.Roof.Light.Wall                 =Strong.Roof.Light.Wall,
    #MAT_Strong.Roof.Salvage.Wall               =Strong.Roof.Salvage.Wall,
    #MAT_Light.Roof.Strong.Wall                 =Light.Roof.Strong.Wall,
    #MAT_Light.Roof.Light.Wall                  =Light.Roof.Light.Wall,
    #MAT_Light.Roof.Salvage.Wall                =Light.Roof.Salvage.Wall,
    #MAT_Salvaged.Roof.Strong.Wall              =Salvaged.Roof.Strong.Wall,
    #MAT_Salvaged.Roof.Light.Wall               =Salvaged.Roof.Light.Wall,
    #MAT_Salvaged.Roof.Salvage.Wall             =Salvaged.Roof.Salvage.Wall,
    #MAT_wall_bamboo                = wall_bamboo,
    #MAT_wall_makeshift             = wall_makeshift,
    #MAT_wall_wood                  = wall_wood,
    #MAT_wall_iron                  = wall_iron,
    #MAT_wall_conc                  = wall_conc,
    #MAT_wall_sum                   = sum_wall,
    #MAT_roof_straw                 = roof_straw,
    #MAT_roof_makeshift             = roof_makeshift,
    #MAT_roof_wood                  = roof_wood,
    #MAT_roof_iron                  = roof_iron,
    #MAT_roof_half_conc             = roof_half_conc,
    #MAT_roof_conc                  = roof_conc,
    #MAT_roof_sum                   = sum_roof,
    #INT_rainfall_landslide          = landslide_per * rainfll_max,
    INT_windspeed_Strong.Roof.Strong.Wall            = vmax_sust_mph * MAT_Strong.Roof.Strong.Wall,  
    INT_windspeed_Strong.Roof.Light.Wall             = vmax_sust_mph * MAT_Strong.Roof.Light.Wall,
    INT_windspeed_Strong.Roof.Salvage.Wall           = vmax_sust_mph * MAT_Strong.Roof.Salvage.Wall,
    INT_windspeed_Light.Roof.Strong.Wall             = vmax_sust_mph * MAT_Light.Roof.Strong.Wall,  
    INT_windspeed_Light.Roof.Light.Wall              = vmax_sust_mph * MAT_Light.Roof.Light.Wall,
    INT_windspeed_Light.Roof.Salvage.Wall            = vmax_sust_mph * MAT_Light.Roof.Salvage.Wall,
    INT_windspeed_Salvaged.Roof.Strong.Wall          = vmax_sust_mph * MAT_Salvaged.Roof.Strong.Wall,  
    INT_windspeed_Salvaged.Roof.Light.Wall           = vmax_sust_mph * MAT_Salvaged.Roof.Light.Wall,
    INT_windspeed_Salvaged.Roof.Salvage.Wall         = vmax_sust_mph * MAT_Salvaged.Roof.Salvage.Wall,
    INT_windspeed_cube_Strong.Roof.Strong.Wall       = vmax_sust_mph^3  * MAT_Strong.Roof.Strong.Wall,  
    INT_windspeed_cube_Strong.Roof.Light.Wall        = vmax_sust_mph^3  * MAT_Strong.Roof.Light.Wall,
    INT_windspeed_cube_Strong.Roof.Salvage.Wall      = vmax_sust_mph^3  * MAT_Strong.Roof.Salvage.Wall,
    INT_windspeed_cube_Light.Roof.Strong.Wall        = vmax_sust_mph^3  * MAT_Light.Roof.Strong.Wall,  
    INT_windspeed_cube_Light.Roof.Light.Wall         = vmax_sust_mph^3  * MAT_Light.Roof.Light.Wall,
    INT_windspeed_cube_Light.Roof.Salvage.Wall       = vmax_sust_mph^3  * MAT_Light.Roof.Salvage.Wall,
    INT_windspeed_cube_Salvaged.Roof.Strong.Wall     = vmax_sust_mph^3  * MAT_Salvaged.Roof.Strong.Wall,  
    INT_windspeed_cube_Salvaged.Roof.Light.Wall      = vmax_sust_mph^3  * MAT_Salvaged.Roof.Light.Wall,
    INT_windspeed_cube_Salvaged.Roof.Salvage.Wall    = vmax_sust_mph^3  * MAT_Salvaged.Roof.Salvage.Wall,
    INT_windspeed_coast_yn                           = vmax_sust_mph * GEO_coast_yn,
    INT_windspeed_cube_coast_yn                      = vmax_sust_mph^3 * GEO_coast_yn,               
    INT_coast_yn_elevation                           = GEO_coast_yn * GEO_elevation_mean
    
  ) %>%
  dplyr::select (index,
                 GEN_mun_code,
                 GEN_prov_name,
                 GEN_mun_name,
                 GEN_typhoon_name,
                 GEO_n_households,
                 GEN_landslide,
                 GEN_landslide_y,
                 GEN_landslide_o,
                 GEN_landslide_r,
                 GEN_stormsurge,
                 GEN_stormsurge_y,
                 GEN_stormsurge_o,
                 GEN_stormsurge_r,
                 WEA_gust_dur,
                 WEA_sust_dur,
                 #WEA_vmax_gust,
                 #WEA_vmax_sust,
                 #WEA_vmax_gust_mhp,
                 WEA_vmax_sust_mhp,
                 #WEA_vmax_gust_sqr,
                 WEA_vmax_sust_sqr,
                 WEA_vmax_sust_cube,
                 #WEA_vmax_gust_cube,
                 WEA_dist_track,
                 #WEA_vmax_sust_mhp,
                 #WEA_windspeed,
                 #WEA_windspeed_squared,
                 #WEA_windspeed_cube,
                 #WEA_rainfall_max,
                 #WEA_rainfall_max1,
                 #WEA_rainfall_sum,
                 GEO_slope_mean,
                 GEO_slope_stdev,
                 GEO_ruggedness_mean,
                 GEO_ruggedness_stdev,
                 GEO_elevation_mean,
                 GEO_coast_length,
                 GEO_coast_yn,
                 GEO_Area,
                 GEO_perimeter,
                 GEO_poverty_perc,
                 MAT_Strong.Roof.Strong.Wall,
                 MAT_Strong.Roof.Light.Wall,
                 MAT_Strong.Roof.Salvage.Wall,
                 MAT_Light.Roof.Strong.Wall,
                 MAT_Light.Roof.Light.Wall,
                 MAT_Light.Roof.Salvage.Wall,
                 MAT_Salvaged.Roof.Strong.Wall,
                 MAT_Salvaged.Roof.Light.Wall,
                 MAT_Salvaged.Roof.Salvage.Wall,
                 #INT_rainfall_landslide,
                 INT_windspeed_Strong.Roof.Strong.Wall,
                 INT_windspeed_Strong.Roof.Light.Wall,
                 INT_windspeed_Strong.Roof.Salvage.Wall,
                 INT_windspeed_Light.Roof.Strong.Wall,
                 INT_windspeed_Light.Roof.Light.Wall,
                 INT_windspeed_Light.Roof.Salvage.Wall,
                 INT_windspeed_Salvaged.Roof.Strong.Wall,
                 INT_windspeed_Salvaged.Roof.Light.Wall,
                 INT_windspeed_Salvaged.Roof.Salvage.Wall,
                 INT_windspeed_cube_Strong.Roof.Strong.Wall,
                 INT_windspeed_cube_Strong.Roof.Light.Wall,
                 INT_windspeed_cube_Strong.Roof.Salvage.Wall,
                 INT_windspeed_cube_Light.Roof.Strong.Wall,
                 INT_windspeed_cube_Light.Roof.Light.Wall,
                 INT_windspeed_cube_Light.Roof.Salvage.Wall,
                 INT_windspeed_cube_Salvaged.Roof.Strong.Wall,
                 INT_windspeed_cube_Salvaged.Roof.Light.Wall,
                 INT_windspeed_cube_Salvaged.Roof.Salvage.Wall,
                 INT_windspeed_coast_yn,
                 INT_windspeed_cube_coast_yn,
                 INT_coast_yn_elevation)
return(data.training)
}